[package]
name = "chirper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.16"
diesel = "2.0.0"
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
